spring.application.name=simsim

spring.datasource.url=jdbc:postgresql://localhost:5432/blog
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql = true

# root application.properties
spring.config.import=optional:classpath:application-minio.properties,optional:classpath:application-auth-db.properties